In [ ]:
import numpy as np

In [18]:
#defining out convolution function that takes 3 dimensional input image and 2 dimensional filter
def Conv(img, filter):
    m_channels, m_rows, m_cols = img.shape
    n_rows, n_cols = filter.shape
    r = np.zeros((m_rows-n_rows+1,m_cols-n_cols+1))
    #print(m_rows, m_cols, m_channels)

    for i in range(m_rows-n_rows+1):
        for j in range(m_cols-n_cols+1):
            for k in range(m_channels):
                r[i,j] += np.sum(np.multiply(img[k,i:n_rows+i,j:n_cols+j], filter))

    return r

In [19]:
#defining our image and filter and calling the convolution function

img = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])

filter = np.array([[1,2],[3,4]])

conv_result = Conv(img, filter)

print(f' The result of convolving image \n {img} \n\n with filter \n {filter}\n\n is: \n {conv_result}')

 The result of convolving image 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] 

 with filter 
 [[1 2]
 [3 4]]

 is: 
 [[111. 141.]
 [201. 231.]]
